import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

//redux
import ReduxProvider from 'src/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Blog Ex',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ReduxProvider>
                    <main className='px-4 md:px-6 prose prose-xl prose-slate dark:prose-invert mx-auto h-screen'>{children}</main>
                </ReduxProvider>
            </body>
        </html>
    );
}
